Fix VPC policy in CAPA controller role CloudFormation template
giantswarm/giantswarm-aws-account-prerequisites pull request #127
Opened 2024-11-12 13:46 UTC by iuriaranda

## Checklist

- [ ] Update changelog in CHANGELOG.md.

2024-11-12 13:49 UTC, fiunchinho submitted a review, later dismissed

2024-11-12 14:10 UTC, iuriaranda commented
I've refactored the CloudFormation template to use managed policies instead of inline, since we were hitting the 10240 bytes limit for inline policies with my recent changes (we were probably hitting that limit already with some installation names). For reference, the `setup.sh` script and Terraform stack were already using managed policies.

2024-11-12 14:12 UTC, fiunchinho requested changes
Maybe worth mentioning it in the changelog

2024-11-13 10:50 UTC, fiunchinho approved these changes

2024-11-13 12:20 UTC, merged